### ISSUE TITLE
ComposerKnowWhereCurrentFileIs must define global variables

### ISSUE THREAD

**Issue by sensorario** [vim-php/vim-composer#15]
This function could just define global variable. The behavior to choose will be responsibility of owner of dotfiles.

If I work with other plugin, maybe I would send them infomations already retrieved by this function, I want to be free to use ComposerKnowWhereCurrentFileIs function and know from it if is necessary or not to run ctags or ctrlp. In case of CtrlP, for example, I dont want to type character by character.

For example we can ask to composer "SomeClassName"

```
SomeClassName
SomeClassNameTest
```

ComposerKnowWhereCurrentFileIs wont open any files, because it will find two lines in composer. But, .. if I work with CtrlP I want to use this function with CtrlP toghether:

```
function! DeveloperPersonalizedFunction()
    call ComposerKnowWhereCurrentFileIs()
    if g:numberOfResults == 1
        call OpenSingleOccurrency()
    else
        call SendCurrentWordToCtrlP()
    endif
endfunction
```

**Comment by gianarb** [comment]
Perfect.. :)
